language: python

dist: focal

python:
  - 3.8

env:
  - PHP_VERSION=7.3
  - PHP_VERSION=7.4
  - PHP_VERSION=8.0
  - PHP_VERSION=8.1

install:
  - sudo ./install-buildah-ubuntu.sh
  - pip install -r requirements.txt
  - buildah login --username $DOCKER_USER --password $DOCKER_PASSWORD $DOCKER_REGISTRY

script:
  - sudo python3 ./build.py $PHP_VERSION --arch arm64,amd64 --build-base --build-cli --build-fpm --build-fpm-apache --build-fpm-nginx --push --debug

jobs:
  include:
    - stage: documentation
      if: (branch = master) AND (NOT (type IN (pull_request)))
      install: skip
      script: "curl https://opensource.byjg.com/add-doc.sh | bash /dev/stdin devops docker-php docs"