FROM byjg/php:8.0-base

LABEL maintainer="Joao Gilberto Magalhaes"

WORKDIR /srv/web

# Install Packages
RUN apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/testing php8-fpm \
 && ln -s /usr/sbin/php-fpm8 /usr/bin/php-fpm \
 && date "+%Y-%m-%d %H:%M:%S" > /etc/build-date

ENV DOCKER_IMAGE byjg/php:8.0-fpm
COPY assets/fpm-nginx/conf/www.conf /etc/php8/php-fpm.d/www.conf
EXPOSE 9000
CMD ["php-fpm", "--nodaemonize"]
