FROM byjg/php:5.6-base

LABEL maintainer="Joao Gilberto Magalhaes"

WORKDIR /srv/web

# Install FPM
RUN apk add --no-cache php5-fpm \
    && ln -s /usr/bin/php-fpm5 /usr/bin/php-fpm \
    && date "+%Y-%m-%d %H:%M:%S" > /etc/build-date

ENV DOCKER_IMAGE byjg/php:5.6-fpm
COPY assets/fpm-nginx/conf/php-fpm.conf /etc/php5/php-fpm.conf
EXPOSE 9000
CMD ["php-fpm", "--nodaemonize"]
