image:
  default: alpine:3.8

version:
  major: 5
  minor: 6
  suffix: 5

extensions:
  - bcmath
  - common
  - ctype
  - curl
  - dba
  - dom
  - exif
  - ftp
  - gd
  - gettext
  - iconv
  - intl
  - json
  - mcrypt
  - mysqli
  - openssl
  - pcntl
  - pdo
  - pdo_dblib
  - pdo_mysql
  - pdo_pgsql
  - pdo_sqlite
  - pear
  - phar
  - posix
  - shmop
  - soap
  - sockets
  - sqlite3
  - xml
  - xmlreader
  - xsl
  - zip
  - zlib

pecl:
  - name: mongodb
    version: 1.7.5
  - name: redis
    version: 2.2.8
  - name: memcached
    version: 2.2.0
  - name: xdebug
    version: 2.5.5
    zend: True
    config:
      - xdebug.remote_port=9001

composer:
  packages:
    - phpunit/phpunit:5.7.*
    - squizlabs/php_codesniffer:*
    - phpmd/phpmd:@stable
  links:
    - phpunit
    - phpcs
    - phpbcbf
    - phpmd

peclBuildPackages:
  - autoconf
  - build-base
  - cyrus-sasl-dev
  - gcc
  - libmemcached-dev
  - libtool
  - make
  - openssl-dev
  - zlib-dev

additionalPackages:
  - libssl1.0
  - libcrypto1.0
  - libmemcached