image:
  default: alpine:3.7

version:
  major: 7
  minor: 1
  suffix: 7

extensions:
  - bcmath
  - common
  - ctype
  - curl
  - dba
  - dom
  - exif
  - ftp
  - gd
  - gettext
  - iconv
  - intl
  - json
  - mbstring
  - mcrypt
  - memcached
  - mysqli
  - mysqlnd
  - openssl
  - pcntl
  - pdo
  - pdo_dblib
  - pdo_mysql
  - pdo_pgsql
  - pdo_sqlite
  - pear
  - phar
  - posix
  - redis
  - session
  - shmop
  - simplexml
  - soap
  - sockets
  - sqlite3
  - tokenizer
  - xdebug
  - xml
  - xmlreader
  - xmlwriter
  - xsl
  - zip
  - zlib

pecl:
  - name: mongodb
  - name: xdebug
    install: False
    zend: True
    config:
      - xdebug.remote_port=9001

composer:
  packages:
    - phpunit/phpunit:*
    - squizlabs/php_codesniffer:*
    - phpmd/phpmd:@stable
  links:
    - phpunit
    - phpcs
    - phpbcbf
    - phpmd

peclBuildPackages:
  - autoconf
  - build-base
  - cyrus-sasl-dev
  - gcc
  - libtool
  - make
  - openssl-dev
  - zlib-dev

additionalPackages:
  - libssl1.0
  - libcrypto1.0

additionalPackagesCli:
  - git
  - openssh-client
