FROM byjg/php:5.6-base

MAINTAINER Joao Gilberto Magalhaes

WORKDIR /srv/web

# Install FPM
RUN apk add --no-cache php5-fpm \
    && ln -s /usr/bin/php-fpm5 /usr/bin/php-fpm

CMD ["php-fpm", "--nodaemonize"]
