FROM byjg/php:5.6-base

LABEL maintainer="Joao Gilberto Magalhaes"

WORKDIR /srv/web

# Install FPM
RUN apk add --no-cache php5-fpm \
    && ln -s /usr/bin/php-fpm5 /usr/bin/php-fpm

ENV DOCKER_IMAGE byjg/php:5.6-fpm
CMD ["php-fpm", "--nodaemonize"]
