FROM byjg/php:7.0-base

LABEL maintainer="Joao Gilberto Magalhaes"

WORKDIR /srv/web

# Install FPM
RUN apk add --no-cache php7-fpm \
    && ln -s /usr/sbin/php-fpm7 /usr/bin/php-fpm

ENV DOCKER_IMAGE byjg/php:7.0-fpm
CMD ["php-fpm", "--nodaemonize"]
