FROM byjg/php:7.2-base

LABEL maintainer="Joao Gilberto Magalhaes"

WORKDIR /srv/web

# Install Packages
RUN apk add --no-cache php7-fpm@php \
 && ln -s /usr/sbin/php-fpm7 /usr/sbin/php-fpm

ENV DOCKER_IMAGE byjg/php:7.2-fpm
CMD ["php-fpm", "--nodaemonize"]
