FROM byjg/php:7.1-base

LABEL maintainer="Joao Gilberto Magalhaes"

WORKDIR /srv/web

# Install Packages
RUN apk add --no-cache php7-fpm \
 && ln -s /usr/sbin/php-fpm7 /usr/bin/php-fpm \
 && date "+%Y-%m-%d %H:%M:%S" > /etc/build-date

ENV DOCKER_IMAGE byjg/php:7.1-fpm
CMD ["php-fpm", "--nodaemonize"]
