FROM byjg/php:7.0-base

LABEL maintainer="Joao Gilberto Magalhaes"

WORKDIR /srv/web

# Install FPM
RUN apk add --no-cache php7-fpm \
    && ln -s /usr/sbin/php-fpm7 /usr/bin/php-fpm

COPY assets/fpm-nginx/conf/www.conf /etc/php7/php-fpm.d/www.conf
EXPOSE 9000
CMD ["php-fpm", "--nodaemonize"]
